"""added a new column in the 'Errata table' named  'erratum_status'.

Revision ID: 381f59bff69b
Revises: d948a71a3c57
Create Date: 2024-04-29 13:16:20.936805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381f59bff69b'
down_revision = 'd948a71a3c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Errata', sa.Column('erratum_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Errata', 'erratum_status')
    # ### end Alembic commands ###
