"""added a new column of available formats in the IVOA table

Revision ID: d948a71a3c57
Revises: 
Create Date: 2024-04-22 14:43:11.924746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd948a71a3c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IVOA',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('concise_name', sa.Text(), nullable=True),
    sa.Column('version_major', sa.Integer(), nullable=True),
    sa.Column('version_minor', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('editors', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('docname', sa.Text(), nullable=False),
    sa.Column('package_path', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('contribute', sa.Text(), nullable=True),
    sa.Column('available_formats', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('docname'),
    sa.UniqueConstraint('docname')
    )
    op.create_table('Errata',
    sa.Column('erratum_id', sa.Integer(), nullable=False),
    sa.Column('erratum_number', sa.Integer(), nullable=True),
    sa.Column('erratum_title', sa.Text(), nullable=True),
    sa.Column('erratum_author', sa.Text(), nullable=True),
    sa.Column('erratum_date', sa.Integer(), nullable=True),
    sa.Column('erratum_accepted_date', sa.Integer(), nullable=True),
    sa.Column('erratum_link', sa.Integer(), nullable=True),
    sa.Column('ivoa_docname', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ivoa_docname'], ['IVOA.docname'], ),
    sa.PrimaryKeyConstraint('erratum_id')
    )
    op.create_table('doi_bibcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('bibcode', sa.Text(), nullable=True),
    sa.Column('ivoa_docname', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ivoa_docname'], ['IVOA.docname'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfc_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfc_link', sa.Text(), nullable=True),
    sa.Column('ivoa_docname', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ivoa_docname'], ['IVOA.docname'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfc_link')
    op.drop_table('doi_bibcode')
    op.drop_table('Errata')
    op.drop_table('IVOA')
    # ### end Alembic commands ###
